---
title: "demographics_explore"
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load-all-libraries, message=FALSE, warning=FALSE, results=FALSE}

# Clean the environment
rm(list=ls())

# Load libraries
library(tidyverse)
library(readxl)
library(ggpubr)
library(rstatix)
library(emmeans)
library(BayesFactor)
library(DT)
library(kableExtra)
library(assortedRFunctions)
library(TOSTER)

# Source other scripts
source('./utils/load_transform_gather.R')

```

# Load and get the datasets ready

```{r load-transform-gather-filter-qc, message=FALSE}

outList <- load_transform_gather()

long_form_data_all_ptp_analyzed <- 
    outList$long_form_data_all_ptp_analyzed
long_form_data_qc_pass_ptp_analyzed <- 
    outList$long_form_data_qc_pass_ptp_analyzed

results_table_all_ptp_analyzed <- 
        outList$results_table_all_ptp_analyzed
results_table_qc_pass_ptp_analyzed <- 
    outList$results_table_qc_pass_ptp_analyzed
results_table_qc_pass_ptp_analyzed_gathered <- 
    outList$results_table_qc_pass_ptp_analyzed_gathered

rm(outList)

```


# Experiment 1

## Age and Sex

```{r age-sex}
# Sex
results_table_all_ptp_analyzed %>% 
        subset(data_submitted == 1 & 
                       status != 'RETURNED' & 
                       status != 'TIMED-OUT' &
                       ptp != 'test' & 
                       progress_state != 'condition not assigned' &
                       experiment == 1) %>% 
        group_by(Sex) %>%
        summarise(count = n()) %>%
        knitr::kable() %>%
        kable_styling(bootstrap_options = "striped")

# Sex QC pass
results_table_qc_pass_ptp_analyzed %>% 
        subset(data_submitted == 1 & status != 'RETURNED' &
                       experiment == 1) %>% 
        group_by(Sex) %>%
        summarise(count = n()) %>%
        knitr::kable() %>%
        kable_styling(bootstrap_options = "striped")
# Age
results_table_all_ptp_analyzed %>% 
        subset(data_submitted == 1 & 
                       status != 'RETURNED' & 
                       status != 'TIMED-OUT' &
                       ptp != 'test' & 
                       progress_state != 'condition not assigned' &
                       experiment == 1) %>% 
        # group_by(congruency) %>%
        get_summary_stats(age, show = c('mean','median','sd','min','max')) %>%
        knitr::kable() %>%
        kable_styling(bootstrap_options = "striped")

# Age QC pass
results_table_qc_pass_ptp_analyzed %>% 
        subset(data_submitted == 1 & status != 'RETURNED' &
                       experiment == 1) %>% 
        # group_by(congruency) %>%
        get_summary_stats(age, show = c('mean','median','sd','min','max')) %>%
        knitr::kable() %>%
        kable_styling(bootstrap_options = "striped")

```

## Why QC Fail:

```{r why-qc-fail}

results_table_all_ptp_analyzed %>% 
        subset(data_submitted == 1 & 
                       experiment == 1) %>%
        group_by(data_submitted,global_pass_incl_phase_2_fails,
                 debrief_qc_pass,fb_int_qc_pass,
                 basic_data_checks_pass,
                 phase_1_rt_qc_pass,phase_2_rt_qc_pass) %>%
        summarize(count = n()) %>%
        knitr::kable() %>%
        kable_styling(bootstrap_options = "striped")

# Break down how many congruent/incongruent passed QC
results_table_qc_pass_ptp_analyzed %>%
        subset(experiment == 1) %>%
        group_by(congruency) %>%
        summarize(count = n()) %>%
        knitr::kable(caption = 'Expt1: N QC Pass by Congruency') %>%
        kable_styling(bootstrap_options = "striped")



```

# Experiment 2

## Age and Sex

```{r age-sex}
# Sex
results_table_all_ptp_analyzed %>% 
        subset(data_submitted == 1 & 
                       status != 'RETURNED' & 
                       status != 'TIMED-OUT' &
                       ptp != 'test' & 
                       progress_state != 'condition not assigned' &
                       experiment == 2) %>% 
        group_by(Sex) %>%
        summarise(count = n()) %>%
        knitr::kable(caption = 'Expt2: sex, all participants') %>%
        kable_styling(bootstrap_options = "striped")

# Sex QC pass
results_table_qc_pass_ptp_analyzed %>% 
        subset(data_submitted == 1 & status != 'RETURNED' &
                       experiment == 2) %>% 
        group_by(Sex) %>%
        summarise(count = n()) %>%
        knitr::kable(caption = 'Expt2: sex, QC-pass participants') %>%
        kable_styling(bootstrap_options = "striped")
# Age
results_table_all_ptp_analyzed %>% 
        subset(data_submitted == 1 & 
                       status != 'RETURNED' & 
                       status != 'TIMED-OUT' &
                       ptp != 'test' & 
                       progress_state != 'condition not assigned' &
                       experiment == 2) %>% 
        # group_by(congruency) %>%
        get_summary_stats(age, show = c('mean','median','sd','min','max')) %>%
        knitr::kable(caption = 'Expt2: Age, all participants') %>%
        kable_styling(bootstrap_options = "striped")

# Age QC pass
results_table_qc_pass_ptp_analyzed %>% 
        subset(data_submitted == 1 & status != 'RETURNED' &
                       experiment == 2) %>% 
        # group_by(congruency) %>%
        get_summary_stats(age, show = c('mean','median','sd','min','max')) %>%
        knitr::kable(caption = 'Expt2: age QC-pass participants') %>%
        kable_styling(bootstrap_options = "striped")

```

## Why QC Fail:

```{r why-qc-fail}

results_table_all_ptp_analyzed %>% 
        subset(data_submitted == 1 &
                       experiment == 2) %>%
        group_by(data_submitted,global_pass_incl_phase_2_fails,
                 debrief_qc_pass,fb_int_qc_pass,
                 basic_data_checks_pass,
                 phase_1_rt_qc_pass,phase_2_rt_qc_pass) %>%
        summarize(count = n()) %>%
        knitr::kable(caption = 'Expt2: QC Fail reasons') %>%
        kable_styling(bootstrap_options = "striped")


# Break down how many congruent/incongruent passed QC
results_table_qc_pass_ptp_analyzed %>%
        subset(experiment == 2) %>%
        group_by(congruency) %>%
        summarize(count = n()) %>%
        knitr::kable(caption = 'Expt1: N QC Pass by Congruency') %>%
        kable_styling(bootstrap_options = "striped")


```

