---
title: "Exploring without the outlier"
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load-all-libraries, message=FALSE, warning=FALSE, results=FALSE}

# Clean the environment
rm(list=ls())

# Load libraries
library(tidyverse)
library(readxl)
library(ggpubr)
library(rstatix)
library(emmeans)
library(BayesFactor)
library(DT)
library(kableExtra)
library(assortedRFunctions)
library(TOSTER)

# Source other scripts
source('./utils/load_transform_gather.R')

```

# Load and get the datasets ready

```{r load-transform-gather-filter-qc, message=FALSE}

outList <- load_transform_gather()

long_form_data_all_ptp_analyzed <- 
    outList$long_form_data_all_ptp_analyzed
long_form_data_qc_pass_ptp_analyzed <- 
    outList$long_form_data_qc_pass_ptp_analyzed

results_table_all_ptp_analyzed <- 
        outList$results_table_all_ptp_analyzed
results_table_qc_pass_ptp_analyzed <- 
    outList$results_table_qc_pass_ptp_analyzed
results_table_qc_pass_ptp_analyzed_gathered <- 
    outList$results_table_qc_pass_ptp_analyzed_gathered

rm(outList)

```


# Calculate with/without outlier:


```{r define-flags}

which_expt <- 1

```


```{r get-ses-1-2-with-and-without-the-outlier}

# Calculate the variables for the full data
st_all_data <- 
        long_form_data_qc_pass_ptp_analyzed %>%
        filter(session %in% c(1,2)) %>%
        droplevels() %>%
        group_by(experiment,
                 congruency,
                 arr_phase_1_name,
                 concept_phase_1,
                 ptp,
                 phase,
                 session) %>% 
        summarise(mean = mean(correct, na.rm = TRUE))
        
        
        
# Now for no outlier
st_no_outlier <- 
        long_form_data_qc_pass_ptp_analyzed %>%
        filter(session %in% c(1,2)) %>% 
        droplevels() %>%
        filter(prompt_point_idx != 1,
               prompt_point_idx != 5) %>% 
        group_by(experiment,
                 congruency,
                 arr_phase_1_name,
                 concept_phase_1,
                 ptp,
                 phase,
                 session) %>%
        summarise(mean = mean(correct, na.rm = TRUE))

# Calculate average for each toy separately
st_by_target <- 
        long_form_data_qc_pass_ptp_analyzed %>%
        filter(session %in% c(1,2)) %>%
        droplevels() %>%
        group_by(experiment,
                 congruency,
                 arr_phase_1_name,
                 concept_phase_1,
                 ptp,
                 phase,
                 session,
                 prompt_img_name) %>%
        summarise(mean = mean(correct, na.rm = TRUE))
        # get_summary_stats(correct,type='mean')

        
```

```{r merge-data-frames}

st <-
        merge(st_all_data,
              st_no_outlier,
              by=c('ptp',
                   'congruency',
                   'concept_phase_1',
                   'phase',
                   'session',
                   'arr_phase_1_name',
                   'experiment'),
              suffixes = c('_all_data',
                           '_no_outlier'),
              all = TRUE)
```

```{r turn-long}
st_long_mean_type <-
        st %>%
        pivot_longer(cols = c(mean_all_data,
                              mean_no_outlier),
                     names_to = 'mean_type',
                     values_to = 'mean_accuracy')

# Now, calculate ses 1 2 average
st_ses_1_2_mean <- 
        st_long_mean_type %>%
        group_by(experiment,
                 congruency,
                 arr_phase_1_name,
                 concept_phase_1,
                 ptp,
                 phase,
                 mean_type) %>%
        summarise(ses_1_2_mean = mean(mean_accuracy, na.rm = TRUE)) %>%
        ungroup() %>%
        mutate(phase = as.character(phase))

st_phase_diff_long <-
        
        st_ses_1_2_mean %>%
        pivot_wider(names_from = phase,
                    names_prefix = 'phase_',
                    values_from = ses_1_2_mean) %>%
        mutate(phase_2_min_phase_1 = phase_2 - phase_1) %>% 
        pivot_longer(cols = c(phase_1,
                              phase_2,
                              phase_2_min_phase_1),
                     names_to = 'phase_type',
                     values_to = 'ses_1_2_mean')

# Ses 1 2 avg for each target
st_by_target_ses_1_2_mean <-
        st_by_target %>%
        group_by(experiment,
                 congruency,
                 arr_phase_1_name,
                 concept_phase_1,
                 ptp,
                 phase,
                 prompt_img_name) %>%
        summarise(ses_1_2_mean = mean(mean, na.rm = TRUE))

# By traget, phase2 min phase1 long form. Only makes sense for the congruent data
st_by_target_phase_diff_long <- 
        st_by_target_ses_1_2_mean %>%
        pivot_wider(names_from = phase,
                    names_prefix = 'phase_',
                    values_from = ses_1_2_mean) %>%
        mutate(phase_2_min_phase_1 = phase_2 - phase_1) %>%
        pivot_longer(cols = c(phase_1,
                              phase_2,
                              phase_2_min_phase_1),
                     names_to = 'phase_type',
                     values_to = 'ses_1_2_mean')        
        


```

# Plots:

## Overall congruency

```{r congruency-plots, fig.height=6, fig.width=6}

st_phase_diff_long %>%
        filter(phase_type == 'phase_2_min_phase_1') %>% 
        ggplot(aes(x=congruency,y=ses_1_2_mean)) +
        geom_violin() +
        geom_boxplot(notch=TRUE,
                     outlier.shape = NA,
                     width=0.4) +
        geom_jitter(width=0.2,
                    alpha=0.2,
                    height = 0) +
        stat_summary(fun=mean, 
                     geom="point",
                     shape=20, 
                     size=5, 
                     color="blue",
                     fill="blue") +    
        geom_hline(yintercept = 0, linetype = 'dashed') +
        facet_grid(experiment~mean_type,
                   labeller = label_both)

```

```{r congruency-bf-expt1-all-data}

# Experiment 1: all data
p2_p1_congruent_1_expt_1_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 1,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_1_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 0,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_1_all_data <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_1_all_data,
        p2_p1_congruent_0_expt_1_all_data,
        paired = FALSE
    ),
    4)

# Experiment 1: all data, arr 1
p2_p1_congruent_1_expt_1_arr_1_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 1,
           arr_phase_1_name == 1,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_1_arr_1_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 0,
           arr_phase_1_name == 1,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_1_arr_1_all_data <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_1_arr_1_all_data,
        p2_p1_congruent_0_expt_1_arr_1_all_data,
        paired = FALSE
    ),
    4)

# Experiment 1: all data, arr 2
p2_p1_congruent_1_expt_1_arr_2_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 1,
           arr_phase_1_name == 2,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_1_arr_2_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 0,
           arr_phase_1_name == 2,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_1_arr_2_all_data <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_1_arr_2_all_data,
        p2_p1_congruent_0_expt_1_arr_2_all_data,
        paired = FALSE
    ),
    4)

# Old way:
# which_expt <- 1
# ses_1_2_perf_congruent_1_arr_1_2 <-
#     results_table_qc_pass_ptp_analyzed %>%
#     filter(experiment == which_expt & congruency == 1) %>%
#     select(phase_2_min_phase_1_ses_1_2_perf) %>% .[[1]]
# 
# ses_1_2_perf_congruent_0_arr_1_2 <-
#     results_table_qc_pass_ptp_analyzed %>%
#     filter(experiment == which_expt & congruency == 0) %>%
#     select(phase_2_min_phase_1_ses_1_2_perf) %>% .[[1]]
# 
# bf_ses_1_2_perf_arr_1_2 <-
#     reportBF(ttestBF(
#         ses_1_2_perf_congruent_1_arr_1_2,
#         ses_1_2_perf_congruent_0_arr_1_2,
#         paired = FALSE
#     ),
#     4)


```



```{r congruency-bf-expt1-no-outlier}
# Experiment 1: no outlier
p2_p1_congruent_1_expt_1_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 1,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_1_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 0,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_1_no_outlier <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_1_no_outlier,
        p2_p1_congruent_0_expt_1_no_outlier,
        paired = FALSE
    ),
    4)


# Experiment 1: no outlier, arr 1
p2_p1_congruent_1_expt_1_arr_1_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 1,
           arr_phase_1_name == 1,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_1_arr_1_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 0,
           arr_phase_1_name == 1,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_1_arr_1_no_outlier <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_1_arr_1_no_outlier,
        p2_p1_congruent_0_expt_1_arr_1_no_outlier,
        paired = FALSE
    ),
    4)

# Experiment 1: all data, arr 2
p2_p1_congruent_1_expt_1_arr_2_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 1,
           arr_phase_1_name == 2,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_1_arr_2_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 1,
           congruency == 0,
           arr_phase_1_name == 2,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_1_arr_2_no_outlier <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_1_arr_2_no_outlier,
        p2_p1_congruent_0_expt_1_arr_2_no_outlier,
        paired = FALSE
    ),
    4)

```


```{r congruency-bf-expt2-all-data}

# Experiment 1: all data
p2_p1_congruent_1_expt_2_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 1,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_2_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 0,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_2_all_data <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_2_all_data,
        p2_p1_congruent_0_expt_2_all_data,
        paired = FALSE
    ),
    4)

# Experiment 1: all data, arr 3
p2_p1_congruent_1_expt_2_arr_3_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 1,
           arr_phase_1_name == 3,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_2_arr_3_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 0,
           arr_phase_1_name == 3,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_2_arr_3_all_data <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_2_arr_3_all_data,
        p2_p1_congruent_0_expt_2_arr_3_all_data,
        paired = FALSE
    ),
    4)

# Experiment 2: all data, arr 4
p2_p1_congruent_1_expt_2_arr_4_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 1,
           arr_phase_1_name == 4,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_2_arr_4_all_data <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 0,
           arr_phase_1_name == 4,
           mean_type == 'mean_all_data',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_2_arr_4_all_data <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_2_arr_4_all_data,
        p2_p1_congruent_0_expt_2_arr_4_all_data,
        paired = FALSE
    ),
    4)

# Old way:
# which_expt <- 1
# ses_1_2_perf_congruent_1_arr_1_2 <-
#     results_table_qc_pass_ptp_analyzed %>%
#     filter(experiment == which_expt & congruency == 1) %>%
#     select(phase_2_min_phase_1_ses_1_2_perf) %>% .[[1]]
# 
# ses_1_2_perf_congruent_0_arr_1_2 <-
#     results_table_qc_pass_ptp_analyzed %>%
#     filter(experiment == which_expt & congruency == 0) %>%
#     select(phase_2_min_phase_1_ses_1_2_perf) %>% .[[1]]
# 
# bf_ses_1_2_perf_arr_1_2 <-
#     reportBF(ttestBF(
#         ses_1_2_perf_congruent_1_arr_1_2,
#         ses_1_2_perf_congruent_0_arr_1_2,
#         paired = FALSE
#     ),
#     4)


```



```{r congruency-bf-expt2-no-outlier}
# Experiment 2: no outlier
p2_p1_congruent_1_expt_2_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 1,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_2_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 0,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_2_no_outlier <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_2_no_outlier,
        p2_p1_congruent_0_expt_2_no_outlier,
        paired = FALSE
    ),
    4)

# Experiment 1: all data, arr 3
p2_p1_congruent_1_expt_2_arr_3_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 1,
           arr_phase_1_name == 3,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_2_arr_3_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 0,
           arr_phase_1_name == 3,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_2_arr_3_no_outlier <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_2_arr_3_no_outlier,
        p2_p1_congruent_0_expt_2_arr_3_no_outlier,
        paired = FALSE
    ),
    4)

# Experiment 2: all data, arr 4
p2_p1_congruent_1_expt_2_arr_4_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 1,
           arr_phase_1_name == 4,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

p2_p1_congruent_0_expt_2_arr_4_no_outlier <-
    st_phase_diff_long %>%
    filter(experiment == 2,
           congruency == 0,
           arr_phase_1_name == 4,
           mean_type == 'mean_no_outlier',
           phase_type == 'phase_2_min_phase_1') %>%
    select(ses_1_2_mean) %>% .[[1]]

bf_expt_2_arr_4_no_outlier <-
    reportBF(ttestBF(
        p2_p1_congruent_1_expt_2_arr_4_no_outlier,
        p2_p1_congruent_0_expt_2_arr_4_no_outlier,
        paired = FALSE
    ),
    4)

```

## By phase:

```{r by-phase, fig.height=7, fig.width=9}

st_phase_diff_long %>%
        filter(phase_type != 'phase_2_min_phase_1') %>%
        ggplot(aes(x=phase_type,y=ses_1_2_mean)) +
        geom_violin() +
        geom_boxplot(notch=TRUE,
                     outlier.shape = NA,
                     width=0.4) +
        geom_point(alpha=0.2) +
        geom_line(aes(group=ptp),
                  alpha = 0.2,
                  linetype = 'solid') +
        stat_summary(fun=mean, 
                     geom="point",
                     shape=20, 
                     size=5, 
                     color="blue",
                     fill="blue") +        
        facet_grid(experiment~mean_type+congruency,
                   labeller = label_both)


```

## Overall congruency by arrangements:

```{r by-arr-with-without-outlier}

st_phase_diff_long %>%
        filter(phase_type == 'phase_2_min_phase_1') %>%
        ggplot(aes(x=congruency,y=ses_1_2_mean)) +
        geom_violin() +
        geom_boxplot(notch=TRUE,
                     outlier.shape = NA,
                     width=0.4) +
        geom_jitter(width=0.2,
                    alpha=0.2,
                    height = 0) +
        stat_summary(fun=mean, 
                     geom="point",
                     shape=20, 
                     size=5, 
                     color="blue",
                     fill="blue") +  
        geom_hline(yintercept = 0, linetype = 'dashed') +
        facet_grid(mean_type~arr_phase_1_name,
                   labeller = label_both) + 
        ylab('Phase 2 min Phase 1')


```

## By phase and by arrangements:

```{r by-arr-and-phase-with-without-outlier, fig.height=8, fig.width=12}

st_phase_diff_long %>%
        filter(phase_type != 'phase_2_min_phase_1') %>%
        ggplot(aes(x=phase_type,y=ses_1_2_mean)) +
        geom_violin() +
        geom_boxplot(notch=TRUE,
                     outlier.shape = NA,
                     width=0.4) +
        geom_point(alpha=0.2) +
        geom_line(aes(group=ptp),
                  alpha = 0.2,
                  linetype = 'solid') +
        stat_summary(fun=mean, 
                     geom="point",
                     shape=20, 
                     size=5, 
                     color="blue",
                     fill="blue") +        
        facet_grid(mean_type~arr_phase_1_name+congruency,
                   labeller = label_both)


```